# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QFileDialog, QMainWindow

from client import Client
import CONSTANTS


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.btnCreateMeeting = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreateMeeting.setObjectName("btnCreateMeeting")
        self.verticalLayout_2.addWidget(self.btnCreateMeeting)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnJoinMeeting = QtWidgets.QPushButton(self.centralwidget)
        self.btnJoinMeeting.setObjectName("btnJoinMeeting")
        self.horizontalLayout_4.addWidget(self.btnJoinMeeting)
        self.lineEditMeetingNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMeetingNumber.setEnabled(False)
        self.lineEditMeetingNumber.setObjectName("lineEditMeetingNumber")
        self.horizontalLayout_4.addWidget(self.lineEditMeetingNumber)
        self.btnConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.btnConfirm.setEnabled(False)
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout_4.addWidget(self.btnConfirm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_OMC = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(26)
        self.label_OMC.setFont(font)
        self.label_OMC.setObjectName("label_OMC")
        self.verticalLayout_2.addWidget(self.label_OMC)
        self.btnShareScreen = QtWidgets.QPushButton(self.centralwidget)
        self.btnShareScreen.setObjectName("btnShareScreen")
        self.verticalLayout_2.addWidget(self.btnShareScreen)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnControlOthersScreen = QtWidgets.QPushButton(self.centralwidget)
        self.btnControlOthersScreen.setObjectName("btnControlOthersScreen")
        self.horizontalLayout.addWidget(self.btnControlOthersScreen)
        self.lineEditPeopleNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPeopleNumber.setEnabled(False)
        self.lineEditPeopleNumber.setObjectName("lineEditPeopleNumber")
        self.horizontalLayout.addWidget(self.lineEditPeopleNumber)
        self.btnConfirmControl = QtWidgets.QPushButton(self.centralwidget)
        self.btnConfirmControl.setEnabled(False)
        self.btnConfirmControl.setObjectName("btnConfirmControl")
        self.horizontalLayout.addWidget(self.btnConfirmControl)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAgree = QtWidgets.QPushButton(self.centralwidget)
        #self.btnAgree.setEnabled(False)
        self.btnAgree.setObjectName("btnAgree")
        self.horizontalLayout_2.addWidget(self.btnAgree)
        self.btnDisagree = QtWidgets.QPushButton(self.centralwidget)
        #self.btnDisagree.setEnabled(False)
        self.btnDisagree.setObjectName("btnDisagree")
        self.horizontalLayout_2.addWidget(self.btnDisagree)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnShareVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btnShareVideo.setObjectName("btnShareVideo")
        self.horizontalLayout_3.addWidget(self.btnShareVideo)
        self.btnShareAudio = QtWidgets.QPushButton(self.centralwidget)
        self.btnShareAudio.setObjectName("btnShareAudio")
        self.horizontalLayout_3.addWidget(self.btnShareAudio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.btnLeave = QtWidgets.QPushButton(self.centralwidget)
        self.btnLeave.setObjectName("btnLeave")
        self.verticalLayout_2.addWidget(self.btnLeave)
        self.btnShowCMM = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowCMM.setObjectName("btnShowCMM")
        self.verticalLayout_2.addWidget(self.btnShowCMM)
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout_2.addWidget(self.btnClose)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_AA = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(26)
        self.label_AA.setFont(font)
        self.label_AA.setObjectName("label_AA")
        self.verticalLayout.addWidget(self.label_AA)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnTransferHost = QtWidgets.QPushButton(self.centralwidget)
        self.btnTransferHost.setObjectName("btnTransferHost")
        self.horizontalLayout_5.addWidget(self.btnTransferHost)
        self.lineEditHostIP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditHostIP.setEnabled(False)
        self.lineEditHostIP.setObjectName("lineEditHostIP")
        self.horizontalLayout_5.addWidget(self.lineEditHostIP)
        self.btnConfirmTrans = QtWidgets.QPushButton(self.centralwidget)
        self.btnConfirmTrans.setEnabled(False)
        self.btnConfirmTrans.setObjectName("btnConfirmTrans")
        self.horizontalLayout_5.addWidget(self.btnConfirmTrans)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnForbidVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btnForbidVideo.setObjectName("btnForbidVideo")
        self.horizontalLayout_6.addWidget(self.btnForbidVideo)
        self.btnPermitVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPermitVideo.setObjectName("btnPermitVideo")
        self.horizontalLayout_6.addWidget(self.btnPermitVideo)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnDorbidAudio = QtWidgets.QPushButton(self.centralwidget)
        self.btnDorbidAudio.setObjectName("btnDorbidAudio")
        self.horizontalLayout_7.addWidget(self.btnDorbidAudio)
        self.btnPermitAudio = QtWidgets.QPushButton(self.centralwidget)
        self.btnPermitAudio.setObjectName("btnPermitAudio")
        self.horizontalLayout_7.addWidget(self.btnPermitAudio)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnForbidScreen = QtWidgets.QPushButton(self.centralwidget)
        self.btnForbidScreen.setObjectName("btnForbidScreen")
        self.horizontalLayout_8.addWidget(self.btnForbidScreen)
        self.btnPermitScreen = QtWidgets.QPushButton(self.centralwidget)
        self.btnPermitScreen.setObjectName("btnPermitScreen")
        self.horizontalLayout_8.addWidget(self.btnPermitScreen)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnCreateMeeting.clicked.connect(MainWindow.btnCreateMeeting_clicked)
        self.btnJoinMeeting.clicked.connect(MainWindow.btnJoinMeeting_clicked)
        self.btnConfirm.clicked.connect(MainWindow.btnConfirm_clicked)
        self.btnShareScreen.clicked.connect(MainWindow.btnShareScreen_clicked)
        self.btnControlOthersScreen.clicked.connect(MainWindow.btnControlOtherScreen_clicked)
        self.btnConfirmControl.clicked.connect(MainWindow.btnConfirmControl_clicked)
        self.btnAgree.clicked.connect(MainWindow.btnAgree_clicked)
        self.btnShareVideo.clicked.connect(MainWindow.btnShareVideo_clicked)
        self.btnShareAudio.clicked.connect(MainWindow.btnShareAudio_clicked)
        self.btnLeave.clicked.connect(MainWindow.btnLeave_clicked)
        self.btnClose.clicked.connect(MainWindow.btnClose_clicked)
        self.btnDisagree.clicked.connect(MainWindow.btnDisagree_clicked)
        self.btnShowCMM.clicked.connect(MainWindow.btnShowCMM_clicked)
        self.btnConfirmTrans.clicked.connect(MainWindow.btnConfirmTrans_clicked)
        self.btnTransferHost.clicked.connect(MainWindow.btnTransferHost_clicked)
        self.btnForbidVideo.clicked.connect(MainWindow.btnForbidVideo_clicked)
        self.btnPermitVideo.clicked.connect(MainWindow.btnPermitVideo_clicked)
        self.btnDorbidAudio.clicked.connect(MainWindow.btnForbidAudio_clicked)
        self.btnPermitAudio.clicked.connect(MainWindow.btnPermitAudio_clicked)
        self.btnForbidScreen.clicked.connect(MainWindow.btnForbidScreen_clicked)
        self.btnPermitScreen.clicked.connect(MainWindow.btnPermitScreen_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.c = Client()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Online Meeting"))
        self.label.setText(_translate("MainWindow", "Welcome to Online Meeting"))
        self.btnCreateMeeting.setText(_translate("MainWindow", "Create Meeting"))
        self.btnJoinMeeting.setText(_translate("MainWindow", "Join Meeting"))
        self.lineEditMeetingNumber.setPlaceholderText(_translate("MainWindow", "Input meeting number..."))
        self.btnConfirm.setText(_translate("MainWindow", "Confirm"))
        self.label_OMC.setText(_translate("MainWindow", "Online Meeting Console"))
        self.btnShareScreen.setText(_translate("MainWindow", "Share Screen"))
        self.btnControlOthersScreen.setText(_translate("MainWindow", "Control Others Screen"))
        self.lineEditPeopleNumber.setPlaceholderText(_translate("MainWindow", "Input people number..."))
        self.btnConfirmControl.setText(_translate("MainWindow", "Confirm"))
        self.btnAgree.setText(_translate("MainWindow", "Agree"))
        self.btnDisagree.setText(_translate("MainWindow", "Disagree"))
        self.btnShareVideo.setText(_translate("MainWindow", "Share Video"))
        self.btnShareAudio.setText(_translate("MainWindow", "Share Audio"))
        self.btnLeave.setText(_translate("MainWindow", "Leave"))
        self.btnShowCMM.setText(_translate("MainWindow", "Show Current Meeting Members"))
        self.btnClose.setText(_translate("MainWindow", "Close"))
        self.label_AA.setText(_translate("MainWindow", "Administrator Assignment"))
        self.btnTransferHost.setText(_translate("MainWindow", "Transfer Host"))
        self.lineEditHostIP.setPlaceholderText(_translate("MainWindow", "Input new host IP..."))
        self.btnConfirmTrans.setText(_translate("MainWindow", "Confirm"))
        self.btnForbidVideo.setText(_translate("MainWindow", "Forbid Video"))
        self.btnPermitVideo.setText(_translate("MainWindow", "Permit Video"))
        self.btnDorbidAudio.setText(_translate("MainWindow", "Forbid Audio"))
        self.btnPermitAudio.setText(_translate("MainWindow", "Permit Audio"))
        self.btnForbidScreen.setText(_translate("MainWindow", "Forbid Screen"))
        self.btnPermitScreen.setText(_translate("MainWindow", "Permit Screen"))


    def __init__(self):
        super().__init__()
        self.setupUi(self)

#-------admin assignments--------------------------------------
    def btnTransferHost_clicked(self):
        self.lineEditHostIP.setEnabled(True)
        self.btnConfirmTrans.setEnabled(True)

    def btnConfirmTrans_clicked(self):
        self.c.hostTransfer(self.lineEditHostIP.text())

    def btnForbidVideo_clicked(self):
        self.c.videoForbid()

    def btnPermitVideo_clicked(self):
        self.c.videoPermit()

    def btnForbidAudio_clicked(self):
        self.c.audioForbid()

    def btnPermitAudio_clicked(self):
        self.c.audioPermit()

    def btnForbidScreen_clicked(self):
        self.c.screenForbid()

    def btnPermitScreen_clicked(self):
        self.c.screenPermit()
#--------------------------------------------------------------

    def btnJoinMeeting_clicked(self):
        '''
        join meeting
        '''
        self.lineEditMeetingNumber.setEnabled(True)
        self.btnConfirm.setEnabled(True)

    def btnCreateMeeting_clicked(self):
        '''
        create meeting
        '''
        self.c.createMeeting()

    def btnConfirm_clicked(self):
        '''
        confirm
        '''
        self.c.joinMeeting(self.lineEditMeetingNumber.text())
        pass

    # def Tow2(self):
    #     from meeting_console import Ui_ConsoleMainWindow
    #     # 做好其他窗口后先import进来后就简单调用就ok了
    #     self.w2 = Ui_ConsoleMainWindow()
    #     self.w2.show()
    #     #self.close()

    def btnShareScreen_clicked(self):
        '''
        share screen
        '''
        if self.c.screenSharing == CONSTANTS.OFF:
            self.c.screenSharingEnable()
        else:
            self.c.screenSharingDisable()

    def btnControlOtherScreen_clicked(self):
        '''
        (Stop) Control other's screen
        '''
        self.lineEditPeopleNumber.setEnabled(True)
        self.btnConfirmControl.setEnabled(True)

    def btnConfirmControl_clicked(self):
        if self.c.screenController == CONSTANTS.OFF:
            self.c.screenControlEnable(self.lineEditPeopleNumber.text())
        else:
            self.c.screenControlDisable()

    def btnAgree_clicked(self):
        if self.c.screenControllerIp == None:
            print("No control request.")
        else:
            self.c.screenControlAgree(self.c.screenControllerIp)

    def btnDisagree_clicked(self):
        if self.c.screenControllerIp == None:
            print("No control request.")
        else:
            self.c.screenControlDisagree(self.c.screenControllerIp)

    def btnShareVideo_clicked(self):
        if self.c.video == CONSTANTS.OFF:
            self.c.videoEnable()
        else:
            self.c.videoDisable()

    def btnShareAudio_clicked(self):
        if self.c.audio == CONSTANTS.OFF:
            self.c.audioEnable()
        else:
            self.c.audioDisable()

    def btnLeave_clicked(self):
        if self.c.state == CONSTANTS.MEETING:
            self.c.leaveMeeting()
        else:
            print("\n CLIENT: You are not in a meeting")

    def btnShowCMM_clicked(self):
        print(self.c.meetingMember)

    def btnClose_clicked(self):
        if self.c.admin:
            self.c.closeMeeting()
        else:
            print("\n CLIENT: You are not an admin")


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    window = Ui_MainWindow()
    window.show()
    sys.exit(app.exec_())